spring:
  application:
    name: client-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # 1 укажите явный маршрут к серверу eureka (serviceUrl)
  instance:
    prefer-ip-address: true
server:
  port: 8083