server:
  port: 4444


spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka} # 1 укажите явный маршрут к серверу eureka (serviceUrl)
  instance:
    prefer-ip-address: true

